create table category(
	CATEGORY_CODE VARCHAR2(50)
	CONSTRAINT PK_CATEGORY_CODE PRIMARY KEY,
	CATEGORY_NAME VARCHAR2(100) 
);

INSERT INTO CATEGORY
VALUES('ctg_001', 'SAMSUNG');

INSERT INTO CATEGORY
VALUES('ctg_002', 'LG');

INSERT INTO CATEGORY
VALUES('ctg_003', 'APPLE');

select *
from category;

DROP TABLE CATEGORY;